tags:
  - name: Curations
    description: 큐레이팅(평가/댓글) 관리 API
paths:
  /styles/{styleId}/curations:
    post:
      summary: 큐레이팅 등록
      description: 특정 스타일에 대한 사용자 피드백과 4가지 항목 점수를 등록합니다
      tags:
        - Curations
      parameters:
        - name: styleId
          in: path
          required: true
          schema:
            type: integer
          description: 큐레이팅 등록할 스타일의 고유 ID
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
                - content
                - password
              properties:
                nickname:
                  type: string
                  description:
                content:
                  type: string
                  description:
                password:
                  type: string
                  description:
                trendy:
                  type: integer
                  minimum: 1
                  maximum: 10
                  description: 트렌디 점수 (1-10)
                personality:
                  type: integer
                  minimum: 1
                  maximum: 10
                  description: 개성 점수 (1-10)
                practicality:
                  type: integer
                  minimum: 1
                  maximum: 10
                  description: 실용성 점수 (1-10)
                cistEffectiveness:
                  type: integer
                  minimum: 1
                  maximum: 10
                  description: 가성비 점수 (1-10)
      responses:
          "200":
            description: 큐레이팅 등록 성공
            content:
              application/json:
                schema:
                  type: object
                  properties:
                    id:
                      type: string
                      example: 123
                    nickname:
                      type: string
                      example: "패피_K"
                    content:
                      type: string
                      example: "전체적인 밸런스가 아주 좋네요!"
                    trendy:
                      type: integer
                      example: 8
                    personality:
                      type: integer
                      example: 7
                    practicality:
                      type: integer
                      example: 9
                    costEffectiveness:
                      type: integer
                      example: 10
                    createdAt:
                      type: string
                      format: date-time
                      example: "2024-02-22T07:47:49.803Z"
          "400":
            description: 유효성 검사 실패
    get:
      summary: 큐레이팅 목록 조회
      tags:
        - Curations
      parameters:
        - name: styleId
          in: path
          required: true
          schema:
            type: integer
        - name: page
          in: query
          required: false
          schema:
            type: integer
            default: 1
        - name: pageSize
          in: query
          required: false
          schema:
            type: integer
            default: 10
        - name: searchBy
          in: query
          schema:
            type: string
            enum:
              - nickname
              - content
        - name: keyword
          in: query
          schema:
            type: string
      responses:
        "200":
          description: 큐레이팅 목록 조회
          content:
            application/json:
              schema:
                type: object
                properties:
                  currentPage: { type: integer }
                  totalPages: { type: integer }
                  totalItemCount: { type: integer }
                  data:
                    ype: array
                    items:
                      type: object
                    properties:
                      id: { type: integer }
                      nickname: { type: string }
                      content: { type: string }
                      trendy: { type: integer, minimum: 0, maximum: 10 }
                      personality: { type: integer, minimum: 0, maximum: 10 }
                      practicality: { type: integer, minimum: 0, maximum: 10 }
                      costEffectiveness: { type: integer, minimum: 0, maximum: 10 }
                      createdAt: { type: string, format: date-time }
                      comment:
                        type: object
                        nullable: true
                        description: "답글 정보 (없을 경우 빈 객체 {} 또는 null)"
                        properties:
                          id: { type: integer }
                          nickname: { type: string }
                          content: { type: string }
                          createdAt: { type: string, format: date-time }
              example:
                currentPage: 1
                totalPages: 5
                totalItemCount: 50
                data:
                  - id: 1
                    nickname: "패션피플"
                    content: "오 이 코디 진짜 힙하네요!"
                    trendy: 9
                    personality: 8
                    practicality: 7
                    costEffectiveness: 6
                    createdAt: "2024-02-22T07:47:49.803Z"
                    comment:
                      id: 123
                      nickname: "작성자"
                      content: "감사합니다! 다음에 더 좋은 코디 가져올게요."
                      createdAt: "2024-02-22T08:00:00.000Z"
                  - id: 2
                    nickname: "미니멀리스트"
                    content: "깔끔해서 따라입기 좋을 것 같아요."
                    trendy: 7
                    personality: 6
                    practicality: 10
                    costEffectiveness: 9
                    createdAt: "2024-02-22T07:47:49.803Z"
                    comment: {}
        "400":
          description: 잘못된 요청입니다

  /curations/{curationId}:
    patch:
      summary: 큐레이팅 수정
      tags:
        - Curations
      parameters:
        - name: curationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - nickname
                - content
                - password
                - trendy
                - personality
                - practicality
                - costEffectiveness
              properties:
                nickname: { type: string }
                content: { type: string }
                password: { type: string, description: "작성 시 입력한 비밀번호" }
                trendy: { type: integer, minimum: 0, maximum: 10 }
                personality: { type: integer, minimum: 0, maximum: 10 }
                practicality: { type: integer, minimum: 0, maximum: 10 }
                costEffectiveness: { type: integer, minimum: 0, maximum: 10 }
      responses:
        "200":
          description: 수정 성공
          content:
            application/json:
              schema:
              example:
                id: 141
                nickname: "철수"
                content: "수정된 스타일 의견입니다."
                trendy: 5
                personality: 5
                practicality: 5
                costEffectiveness: 5
                createdAt: "2025-12-23T10:00:00.000Z"
        "400":
          description: 잘못된 요청입니다
        "403":
          description: 비밀번호가 틀렸습니다
        "404":
          description: 존재하지 않습니다

    delete:
      summary: 큐레이팅 삭제
      tags:
        - Curations
      parameters:
        - name: curationId
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - password
              properties:
                password:
                  type: string
                  description: 큐레이팅 비밀번호
      responses:
        "200":
          description: 큐레이팅 삭제 성공
        "400":
          description: 잘못된 요청입니다
        "403":
          description: 비밀번호가 틀렸습니다
        "404":
          description: 존재하지 않습니다
